"use client";

import { motion } from "framer-motion";
import styles from "./Footer.module.css";

/**
 * Bento-grid footer with project info, how-it-works, links, and CTA cards.
 */
export default function Footer() {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <footer className={styles.footer}>
      <div className={styles.grid}>
        {/* About Card */}
        <motion.div
          className={`${styles.card} ${styles.aboutCard}`}
          whileHover={{ y: -3 }}
          transition={{ duration: 0.2 }}
        >
          <h3 className={styles.cardTitle}>VÉRA</h3>
          <p className={styles.cardText}>
            NLP-powered greenwashing detection for fashion. Analyze product
            sustainability claims with AI and get a transparent eco-score.
          </p>
        </motion.div>

        {/* How It Works Card */}
        <motion.div
          className={`${styles.card} ${styles.howCard}`}
          whileHover={{ y: -3 }}
          transition={{ duration: 0.2 }}
        >
          <h3 className={styles.cardTitle}>How It Works</h3>
          <div className={styles.steps}>
            <div className={styles.step}>
              <span className={styles.stepNum}>1</span>
              <span>Paste URL</span>
            </div>
            <div className={styles.step}>
              <span className={styles.stepNum}>2</span>
              <span>AI Analysis</span>
            </div>
            <div className={styles.step}>
              <span className={styles.stepNum}>3</span>
              <span>Get Score</span>
            </div>
          </div>
        </motion.div>

        {/* Links Card */}
        <motion.div
          className={`${styles.card} ${styles.linksCard}`}
          whileHover={{ y: -3 }}
          transition={{ duration: 0.2 }}
        >
          <h3 className={styles.cardTitle}>Links</h3>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.link}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
            </svg>
            GitHub
          </a>
          <p className={styles.credit}>Built by Arin Pattnaik</p>
        </motion.div>

        {/* CTA Card */}
        <motion.div
          className={`${styles.card} ${styles.ctaCard}`}
          whileHover={{ y: -3 }}
          transition={{ duration: 0.2 }}
        >
          <h3 className={styles.cardTitle}>Ready to scan?</h3>
          <button className={styles.ctaBtn} onClick={scrollToTop}>
            Try a demo scan ↑
          </button>
        </motion.div>
      </div>

      <p className={styles.disclaimer}>
        Scores are generated by NLP analysis and should be used as guidance.
        Always verify claims through official certification databases.
      </p>
    </footer>
  );
}
